[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
headless = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"